# Generated by Django 5.1.3 on 2024-11-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider1', models.ImageField(blank=True, null=True, upload_to='images/profile_pics')),
                ('slider2', models.ImageField(blank=True, null=True, upload_to='images/profile_pics')),
                ('slider3', models.ImageField(blank=True, null=True, upload_to='images/profile_pics')),
                ('slider4', models.ImageField(blank=True, null=True, upload_to='images/profile_pics')),
                ('slider5', models.ImageField(blank=True, null=True, upload_to='images/profile_pics')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='images/profile_pics')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='images/profile_pics')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='images/profile_pics')),
            ],
        ),
        migrations.CreateModel(
            name='logoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lightLogo', models.ImageField(blank=True, null=True, upload_to='images/profile_pics')),
            ],
        ),
    ]
