# Generated by Django 5.1.3 on 2024-11-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homemodel',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='homemodel',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='homemodel',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='homemodel',
            name='slider1',
        ),
        migrations.RemoveField(
            model_name='homemodel',
            name='slider2',
        ),
        migrations.RemoveField(
            model_name='homemodel',
            name='slider3',
        ),
        migrations.RemoveField(
            model_name='homemodel',
            name='slider4',
        ),
        migrations.RemoveField(
            model_name='homemodel',
            name='slider5',
        ),
        migrations.AddField(
            model_name='homemodel',
            name='desc',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/about'),
        ),
        migrations.AddField(
            model_name='homemodel',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='logomodel',
            name='lightLogo',
            field=models.ImageField(blank=True, null=True, upload_to='images/logo'),
        ),
    ]
