# Generated by Django 5.1.3 on 2024-11-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_homemodel_image1_remove_homemodel_image2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('desc', models.TextField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/about')),
            ],
        ),
        migrations.RemoveField(
            model_name='homemodel',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='homemodel',
            name='image',
        ),
        migrations.RemoveField(
            model_name='homemodel',
            name='title',
        ),
        migrations.AddField(
            model_name='homemodel',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile_pics'),
        ),
        migrations.AddField(
            model_name='homemodel',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile_pics'),
        ),
        migrations.AddField(
            model_name='homemodel',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile_pics'),
        ),
        migrations.AddField(
            model_name='homemodel',
            name='slider1',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile_pics'),
        ),
        migrations.AddField(
            model_name='homemodel',
            name='slider2',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile_pics'),
        ),
        migrations.AddField(
            model_name='homemodel',
            name='slider3',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile_pics'),
        ),
        migrations.AddField(
            model_name='homemodel',
            name='slider4',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile_pics'),
        ),
        migrations.AddField(
            model_name='homemodel',
            name='slider5',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile_pics'),
        ),
    ]
