# Generated by Django 5.1.3 on 2024-11-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_aboutus_remove_homemodel_desc_remove_homemodel_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
