# Generated by Django 5.1.3 on 2024-11-14 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_aboutus_p1_aboutus_p2_aboutus_p3_aboutus_p4_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='desc',
        ),
    ]
