# Generated by Django 5.1.3 on 2024-11-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='heading1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='heading2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='heading3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
