# Generated by Django 5.1.3 on 2024-11-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufactormodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='images/manufacctor')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='images/manufacctor')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='images/manufacctor')),
            ],
        ),
    ]
