# Generated by Django 5.1.3 on 2024-11-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_manufactormodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(blank=True, max_length=200, null=True)),
                ('insta', models.CharField(blank=True, max_length=200, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
